/**
 * Scripted `Interaction` + a spawner that can never open a browser.
 *
 * Two doubles, both structural rather than promises to behave — see AGENTS.md §Testing and
 * `agent-patterns/alchemy-test-patterns.md`:
 *
 * 1. **`scriptedInteraction`** answers prompts from a queue and records every prompt and message, so
 *    a flow's *questions* are assertable (`asked()`), not just its effects. An unscripted prompt is
 *    a **defect**, not a hang: it means the flow changed and the test must be updated, which is the
 *    failure mode you want in CI.
 * 2. **`noBrowserSpawner`** replaces `ChildProcessSpawner`, because `openUrl` spawns the platform
 *    opener (`open`, `xdg-open`) with the authorize URL. That is not hygiene — the first mutation
 *    campaign over `AuthProvider.ts` routed tests into the browser OAuth flow and opened **dozens of
 *    real browser windows** pointing at a callback server that was already closed, so every window
 *    showed "connection refused". Faking the spawner makes that impossible rather than unlikely.
 *
 * Extracted from `tests/auth/profile-flows.test.ts` (2026-09-22) so the AuthProvider OAuth-login
 * tests use the same doubles instead of a second implementation.
 */
import * as Effect from 'effect/Effect'
import * as Layer from 'effect/Layer'
import { ChildProcessSpawner } from 'effect/unstable/process/ChildProcessSpawner'
import { Interaction } from 'alchemy/Interaction'

export interface Script {
  readonly select?: Array<Answer<unknown>>
  readonly password?: Array<Answer<string>>
  readonly text?: Array<Answer<string>>
  readonly confirm?: Array<Answer<boolean>>
  /**
   * Leave the `text` prompt unanswered (it never completes unless the script supplies an answer
   * first). That is how the **other** arm of `loginOAuth`'s race — the loopback callback — gets to
   * win in a test: the paste prompt is started either way, so it must not complete.
   */
  readonly hangText?: boolean
}

/** One offered choice, recorded so a test can assert the *labels* the user saw. */
export interface RecordedOption {
  readonly value: unknown
  readonly label?: unknown
  readonly description?: unknown
}

export interface RecordedPrompt {
  readonly kind: string
  readonly message: string
  /** The choices each `select` offered, so a test can pin exactly what the user saw. */
  readonly options?: ReadonlyArray<RecordedOption>
  /** Just the values, for the common "which arms were offered" assertion. */
  readonly optionValues?: ReadonlyArray<unknown>
  readonly initialValue?: unknown
  /** The greyed-out hint a text prompt shows (e.g. "the browser will complete this"). */
  readonly placeholder?: unknown
}

/**
 * An answer may be a value, or a function of what the flow has said so far.
 *
 * The lazy form exists for prompts whose correct answer is only knowable at prompt time — the
 * documented OAuth path is "paste the callback URL", and its `state` is generated by the flow and
 * narrated in the authorize URL an instant earlier.
 */
export type Answer<T> = T | ((context: AnswerContext) => T)

export interface AnswerContext {
  readonly notes: ReadonlyArray<{ kind: string; message: string }>
  readonly prompts: ReadonlyArray<RecordedPrompt>
}

/** A recording, scripted `Interaction`: prompts come from `script`, everything is recorded. */
export const scriptedInteraction = (script: Script) => {
  const prompts: Array<RecordedPrompt> = []
  const notes: Array<{ kind: string; message: string }> = []

  const answer = <T>(
    kind: string,
    message: string,
    queue: Array<Answer<T>> | undefined,
    extra?: {
      options?: ReadonlyArray<RecordedOption>
      optionValues?: ReadonlyArray<unknown>
      initialValue?: unknown
      placeholder?: unknown
    },
    validate?: (value: T) => string | undefined,
  ): Effect.Effect<T> => {
    prompts.push({ kind, message, ...extra })
    if (kind === 'text' && script.hangText === true) return Effect.never
    const queued = queue?.shift()
    // A defect (not a typed failure): an unscripted prompt means the flow changed.
    if (queued === undefined) return Effect.die(new Error(`unscripted ${kind} prompt: ${message}`))
    const next = typeof queued === 'function' ? (queued as (c: AnswerContext) => T)({ notes, prompts }) : queued
    // The real terminal re-prompts until a prompt's own validator is happy, so an answer the
    // flow would reject (an empty API key) must not sail through here either.
    const issue = validate?.(next)
    return issue === undefined
      ? Effect.succeed(next)
      : Effect.die(new Error(`${kind} prompt rejected the answer: ${issue}`))
  }
  const note = (kind: string) => (message: string | { message: string }) =>
    Effect.sync(() => {
      notes.push({ kind, message: typeof message === 'string' ? message : message.message })
    })

  const service = {
    output: {
      info: note('info'),
      success: note('success'),
      warning: note('warning'),
      error: note('error'),
    },
    prompt: {
      select: (options: {
        message: string
        options: ReadonlyArray<{ value: unknown; label?: unknown; description?: unknown }>
        initialValue?: unknown
      }) =>
        answer('select', options.message, script.select, {
          options: options.options.map((option) => ({
            value: option.value,
            label: option.label,
            description: option.description,
          })),
          optionValues: options.options.map((option) => option.value),
          initialValue: options.initialValue,
        }),
      password: (options: { message: string; validate?: (value: string) => string | undefined }) =>
        answer('password', options.message, script.password, undefined, options.validate),
      text: (options: {
        message: string
        validate?: (value: string) => string | undefined
        initialValue?: unknown
        placeholder?: unknown
      }) =>
        answer(
          'text',
          options.message,
          script.text,
          { initialValue: options.initialValue, placeholder: options.placeholder },
          options.validate,
        ),
      confirm: (options: { message: string }) => answer('confirm', options.message, script.confirm),
      multiSelect: (options: { message: string }) => answer('multiSelect', options.message, undefined),
      awaitExternal: (options: { message: string }) => answer('awaitExternal', options.message, undefined),
    },
  }

  return {
    prompts,
    notes,
    layer: Layer.succeed(Interaction, service as never),
    /** Assert the prompts, in order, as `kind: message` pairs. */
    asked: () => prompts.map((prompt) => `${prompt.kind}: ${prompt.message}`),
  }
}

/**
 * A fake `ChildProcessSpawner`: records the spawn instead of running it, so `openUrl` can never
 * launch a real browser. Only `exitCode` is read by `openUrl` (0 = the browser opened) — the stdio
 * members are never touched — so this is a structural double (cast once).
 */
export const noBrowserSpawner = (options: { exitCode?: number } = {}) => {
  const spawned: Array<unknown> = []
  const handle = {
    pid: 1,
    exitCode: Effect.succeed(options.exitCode ?? 0),
    isRunning: Effect.succeed(false),
    kill: () => Effect.void,
  }
  return {
    spawned,
    layer: Layer.succeed(ChildProcessSpawner, {
      spawn: (command: unknown) =>
        Effect.sync(() => {
          spawned.push(command)
          return handle
        }),
    } as never),
  }
}
